#ifndef PATH_PLANNER
#define PATH_PLANNER

#include <vector>
#include <queue>
#include <cmath>
#include <utility>
#include <limits>
#include <optional>
#include <mutex>

#include "rclcpp/rclcpp.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"
#include "geometry_msgs/msg/pose_with_covariance_stamped.hpp"
#include "nav_msgs/msg/occupancy_grid.hpp"
#include "nav_msgs/msg/path.hpp"
#include "tf2_ros/buffer.h"
#include "tf2_ros/transform_listener.h"
#include "visualization_msgs/msg/marker.hpp"

namespace chapt10_planner
{
    /**
     * @brief Represents a single cell in the grid map used for path planning.
     */
    struct GridNode
    {
        int index;              ///< Unique index of the cell in the 1D map vector.
        double g_cost;          ///< Distance from the start node to this node.
        double h_cost;          ///< Heuristic distance estimate to the target node.
        double f_cost;          ///< Total cost (g + h).
        int parent_index;       ///< Index of the previous node in the path (-1 if none).
        int already_visited;    ///< Search ID to check if node was visited in current iteration.

        /**
         * @brief Struct constructor (safe initialization of GridNode).
         */
        GridNode()
        : index(-1), g_cost(INFINITY), h_cost(INFINITY), f_cost(INFINITY), parent_index(-1), already_visited(-1){}
    };

    /**
     * @brief Compare functor for priority queue nodes.
     */
    struct CompareNodes
    {
        /**
         * @brief Compare operator of two nodes (Min-Heap).
         * * @param a First node to be compared.
         * @param b Second node to be compared.
         * @return true if f_cost of 'a' node is greater than 'b' (order change for Min-Queue)
         * @return false otherwise
         */
        bool operator()(const GridNode& a, const GridNode& b)
        {
            return a.f_cost > b.f_cost;
        }
    };

    /**
    * @brief Global path planner implementing the A* algorithm along with path relaxation (smoothing).
    * * @details The path calculation is performed asynchronously to ensure non-blocking.
    * from the start pose to the goal pose received from rviz2 visualization based on the occupancy grid map.
    * It subscribes to /map, /goal_pose and /initialpose topics and publishes the path to /path along with algorith expansion visualization data to /draw.
    * 
    */
    class PathPlanner : public rclcpp::Node
    {
    public:

        /**PathPlanner class contructor */
        PathPlanner();

        /**
         * @brief Core function od class implementing A* algorithm publishing results along with visualization data.
         * * @details Returned path is already post processed by smooth_path() method. This method is computationally intensive and designed to be executed in a separate thread (via std::async).
         * @param inflated_map std::shared_ptr<nav_msgs::msg::OccupancyGrid>, inflated map
         * @return std::optional<std::vector<geometry_msgs::msg::PoseStamped>> Post proccesed A* generated path.
         */
        std::optional<std::vector<geometry_msgs::msg::PoseStamped>> find_path(std::shared_ptr<nav_msgs::msg::OccupancyGrid> inflated_map);

        /**
         * @brief Inflates obstacles on the map based on robot_radius_ and boundry_safety_margin_ parameters.
         * @param map const nav_msgs::msg::OccupancyGrid::SharedPtr &map, Reference to original occupancy grid map.
         * @return nav_msgs::msg::OccupancyGrid::SharedPtr Inflated map.
         */ 
        nav_msgs::msg::OccupancyGrid::SharedPtr inflate_map(const nav_msgs::msg::OccupancyGrid::SharedPtr &map);

        /**
         * @brief Post process the path to make it smooth.
         * * @details Provide relaxation of the path using simple 
         * @param path  Reference to raw path generated by A* algorithm.
         * @param inflated_map Reference to inflated map grid.
         * @return std::vector<geometry_msgs::msg::PoseStamped> Smoothed path
         */
        std::vector<geometry_msgs::msg::PoseStamped> smooth_path(std::vector<geometry_msgs::msg::PoseStamped> &path, nav_msgs::msg::OccupancyGrid::SharedPtr &inflated_map);

    private:

        /**
         * @brief Calculates distance in straight line between two grid nodes.
         * * @details Index is number indicating position bu in linearised representation od grid structure.
         * @param start_index Index of first point.
         * @param end_index Index of second point.
         * @param width Width of the map.
         * @return Distance in straight line between two passed points in non linearised grid index metrics.
         */
        double calculate_distance(int start_index, int end_index, int width) const;

        /**
         * @brief Checks if passed index belongs to map.
         * * @details Index is number indicating position but in linearised representation od grid structure.
         * @param index Index of element of the grid.
         * @param width Width of the map.
         * @param height Height of the map.
         * @return True if index belongs to map.
         * @return False othervise.
         */
        bool index_belong_to_map(int index, int width, int height) const;

        /**
         * @brief Checks if passed index is obstacle on the map.
         * * @details Index is number indicating position but in linearised representation od grid structure.
         * @param index Index of element of the grid.
         * @param map const nav_msgs::msg::OccupancyGrid::SharedPtr &map, Reference to original occupancy grid map.
         * @return True if index isn't an obstacle, false if it is.
         */
        bool not_obstacle(int index,const nav_msgs::msg::OccupancyGrid::SharedPtr &map) const;

        /**
         * @brief Checks if passed indexes belongs to map.
         * * @details Indexes are in non linearized grid metrics (x,y).
         * @param x Index of x asis.
         * @param y Index of y asis.
         * @param width Width of the map.
         * @param height Height of the map.
         * @return True if coordinates belong to grid.
         * @return False if they don't. 
         */
        bool coordinates_validation(int x, int y, int width, int height) const;

        /**
         * @brief Converts pose from word coordinates metrics into linearised index metrics.
         * @param x X position in world metrics.
         * @param y Y position in world metrics.
         * @param origin_x X coordinate of origin of the used map.
         * @param origin_y Y coordinate of origin of the used map.
         * @param resolution Resolution of the used map.
         * @param width Width of the map.
         * @return Index value.
         */
         int world_to_index(double x, double y, double origin_x, double origin_y, float resolution, int width) const;

        /**
         * @brief Converts index linearised metrics into grid (x,y) index metrics.
         * @param index Index in linearised metrics.
         * @param width Width of the map.
         * @return std::pair<int, int> A pair of x,y indexes.
         */
        std::pair<int, int> index_to_grid(int index, int width) const;

        /**
         * @brief Prepare and publishes data for drawing algorithm expansion in rviz2.
         * * @details It's indicator how fast our visialization would draw expansion.
         * @param draw_expansion_buffer Referencvce to vector with indexes of elements to be drawn.
         */
        void draw_expansion(std::vector<int> &draw_expansion_buffer) const;

        /**
         * @brief Clears map from markers generated during agorithm expansion visualization.
         */
        void clear_map() const;

        /**
         * @brief Draws start pose as square on the map and erase old path.
         * * @details This type od architecture is essential in this case due to the fact that rviz2 doesn't erase old path when sending empty one so draw-erase functionalities are conected
         * 
         */
        void erase_path_and_draw_start() const;

        /**
         * @brief Packs and publishes final path data to /path topic.
         * @param path Reference to the vector of PoseStamped ros msgs struct which constructs the final path.
         */
        void path_publish(const std::vector<geometry_msgs::msg::PoseStamped> &path) const;

        // ### ROS2 COMMUNICATIONS ###

        /**Parameters on change callback handle. */
        rclcpp::node_interfaces::OnSetParametersCallbackHandle::SharedPtr param_callback_handle_;

        /**Subscription of ROS map toopic. */
        rclcpp::Subscription<nav_msgs::msg::OccupancyGrid>::SharedPtr map_sub_;
        
        /**Subscription of start position indication. */
        rclcpp::Subscription<geometry_msgs::msg::PoseWithCovarianceStamped>::SharedPtr start_pose_sub_;

        /**Subscription of target position indication. */
        rclcpp::Subscription<geometry_msgs::msg::PoseStamped>::SharedPtr target_pose_sub_;

        /**Publisher responsible for publishing visualization data. */
        rclcpp::Publisher<visualization_msgs::msg::Marker>::SharedPtr drawing_pub_;

        /**Publisher responsible for publishing path data */
        rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr path_pub_;

        /**Quality of service policy for map subscription. */
        rclcpp::QoS qos_policy_map_;

        /**Quality of service policy for rviz2 vizualization drawing. */
        rclcpp::QoS qos_policy_drawing_;

        /**Quality of services for other pub/sub */
        rclcpp::QoS qos_policy_;

        /**Timer responsible for drawing visualization along with cheching if calculation thread ended obtaining path */
        rclcpp::TimerBase::SharedPtr check_if_path_solved_;

        // ### CLASS ATRIBUTES ###

        /**Class atribute with orginal map */
        nav_msgs::msg::OccupancyGrid::SharedPtr map_;

        /**Ros map on wich are proceded all calculations. */
        nav_msgs::msg::OccupancyGrid::SharedPtr inflated_map_;

        /**Handle to async task of finding path */
        std::future<std::optional<std::vector<geometry_msgs::msg::PoseStamped>>> planning_future_;

        /**Start position captured by start_pose_sub_. */
        geometry_msgs::msg::PoseWithCovarianceStamped start_pose_;

        tf2_ros::Buffer tf_buffer_;
        tf2_ros::TransformListener tf_listener_;

        /**Target position captured by target_pose_sub_. */
        geometry_msgs::msg::PoseStamped target_pose_;

        /** Final path */
        std::vector<geometry_msgs::msg::PoseStamped> path_;

        /** Map containing current A* algorithm expansion status. */
        std::vector<GridNode> map_nodes_;

        /** Calculation buffer in smooth_path() metode.*/
        std::vector<std::pair<double, double>> old_state_;

        /** Calculation buffer in smooth_path() metode.*/
        std::vector<std::pair<double, double>> new_state_;

        /** Buffer containing expansion draw data */
        std::vector<std::vector<int>> shared_expansion_draw_buffer_;

        /** Mutex protecting access to shared_expansion_draw_buffer_ between the worker thread (A*) and the visualization timer. */
        std::mutex drawing_mutex_;

        /**Search iteration identifier */
        int search_id_;

        /**Flag indicating id we received start_pose_ */
        bool start_pose_received_;


        //### PARAMETERS ###

        /**Robot radius in meters */
        double robot_radius_;

        /**Frame if name from parameter value */
        std::string frame_id_;

        /**Expansion buffer size parameter value, (indicates how fast expansion visualization would be drawn)*/
        int expansion_draw_buffer_size_;

        /**Height of marker in rviz2 visualization from parameter value*/
        double marker_height_;

        /**Color of marker in rviz2 from parameter value */
        std::vector<double> marker_color_rgb_;

        /**Smoothing factor for path post processing */
        double smoothing_factor_;

        /**Boundry safety margin for map inflation in meters */
        double boundary_safety_margin_;
    };
}
#endif