mpc_node:
  ros__parameters:
    use_sim_time: true
    debug_info: false
    delay_mode: true
    max_speed: 0.25
    controller_freq: 20.0
    goal_radius: 0.10
    downsample_rate: 10
    mpc_steps: 20.0
    mpc_ref_cte: 0.0
    mpc_ref_vel: 0.30
    mpc_ref_etheta: 0.0
    mpc_w_cte: 1000.0
    mpc_w_etheta: 1000.0
    mpc_w_vel: 100.0
    mpc_w_angvel: 100.0
    mpc_w_angvel_d: 10.0
    mpc_w_accel: 50.0
    mpc_w_accel_d: 10.0
    mpc_max_angvel: 1.2
    mpc_max_throttle: 1.0
    mpc_bound_value: 1.0e3
    path_topic: /path
    twist_topic: /cmd_vel
    mpc_path_topic: /mpc_path
    map_frame: map
    odom_frame: map
    robot_frame: base_footprint
